### ISSUE TITLE
请教下系统如何部署

### ISSUE THREAD

**Issue by leslieeilsel** [yanglinyun/vue_wenjuan#1]
前后台分别跑在8005/8004端口下，运行项目之后登陆报错。
`POST http://127.0.0.1:8005/api/login 404 (Not Found)`

**Comment by yanglinyun** [comment]
前端需要在apache配置后端api代理 
具体请看这篇文章
[vue项目部署到apache过程及所遇相关问题](https://blog.csdn.net/weixin_42043407/article/details/115391787)
